##
##  Makefile -- Build procedure for sample yabaic Apache module
##  Autogenerated via ``apxs -n yabaic -g''.
##

builddir=.
top_srcdir=/etc/apache2
top_builddir=/etc/apache2
include /usr/lib/apache2/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=/etc/init.d/apache2

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
INCLUDES=-I/usr/local/include/
LIBS=-L/usr/local/lib/ -lmemcached

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_yabaic.o mod_yabaic.lo mod_yabaic.slo mod_yabaic.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/yabaic

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	sudo $(APACHECTL) start
restart:
	sudo $(APACHECTL) restart
stop:
	sudo $(APACHECTL) stop

