/* 
**  mod_yabaic.c -- Apache sample yabaic module
**  [Autogenerated via ``apxs -n yabaic -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_yabaic.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /yabaic in as follows:
**
**    #   apache2.conf
**    LoadModule yabaic_module modules/mod_yabaic.so
**    <Location /yabaic>
**    SetHandler yabaic
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /yabaic and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/yabaic 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_yabaic.c
*/ 
#include <stdlib.h>

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

#include <libmemcached/memcached.h>

#define yabasa_key "yabasa"
#define EXPIRE_TIME 86400


struct YABAI_MEMCACHED
{
  memcached_st *memc;
  memcached_return rc;
};

struct YABAI_MEMCACHED yabaimcst;



void yabaiassert(struct YABAI_MEMCACHED *y)
{
  if (y->rc != MEMCACHED_SUCCESS){
    fprintf(stderr, "%s\n", memcached_strerror(y->memc, y->rc));
  }
}


/* The sample content handler */
static int yabaic_handler(request_rec *r)
{
  char buf[256];
  char* rcv;
  unsigned long yabasa;
  size_t value_length;
  uint32_t flags = 0;

  if (strcmp(r->handler, "yabaic")) {
      return DECLINED;
  }
  r->content_type = "text/html";

  if(!r->header_only)
  {
    rcv = memcached_get(yabaimcst.memc, 
                         yabasa_key, strlen(yabasa_key), 
                         &value_length, &flags, 
                         &yabaimcst.rc);
    yabaiassert(&yabaimcst);
    if(NULL != rcv){
      yabasa = atol(rcv);
      free(rcv);
      snprintf(&buf[0], sizeof(buf), "%ld", ++yabasa);
    }
    else{
      strncpy(buf, "1\0", sizeof(buf));
    }

    yabaimcst.rc = memcached_set(yabaimcst.memc, 
                                  yabasa_key, strlen(yabasa_key), 
                                  buf, strlen(buf), 
                                  (time_t)EXPIRE_TIME, (time_t)0);
    yabaiassert(&yabaimcst);
    ap_rputs("test mod_yabaic.c; sushi:", r);
    ap_rputs(buf, r);
  }

  return OK;
}


static void yabaic_register_hooks(apr_pool_t *p)
{
  struct memcached_server_st *servers;

  yabaimcst.memc = memcached_create(NULL);
  yabaiassert(&yabaimcst);

  servers = memcached_server_list_append(NULL, "localhost", 11211, &yabaimcst.rc);
  yabaiassert(&yabaimcst);
  yabaimcst.rc = memcached_server_push(yabaimcst.memc, servers);
  yabaiassert(&yabaimcst);

  memcached_server_list_free(servers);

  ap_hook_handler(yabaic_handler, NULL, NULL, APR_HOOK_MIDDLE);
  fprintf(stderr, "--mod_yabai.c--\n");
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA yabaic_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    yabaic_register_hooks  /* register hooks                      */
};

